### ISSUE TITLE
Missing Channels VOX, ARD... Zattoo Box 1.0.0 XBMC/RasperryPi

### ISSUE THREAD

**Issue by ghost** [nancpasc/ZattooBox#10]
Hy

since one or two weeks some Channels are missing, fe VOX, ARD...
Reinstall and Reboot doesnt help. On iPad-Zattoo-App everything is alright. Ist there an issue? Can you help me?

Thank you very much!
Best regards
Ben

Hallo

seit ien oder zweich Wochen fehlen ien paar kanäle zb VOX, ARD...
Neuinstallation, Downgrade auf 0.5 und Neustart hilft nicht. In den offiziellen Zatto Apps passt alles. Gibts da ein Problem? Hats du mir einen Tipp?

Vielen Dank!

**Comment by nancpasc** [comment]
Hi,

Can it be related to this ?

https://support.zattoo.com/hc/en-us/articles/202249726-Why-is-Silverlight-required-HiQ-DE-

I doubt Kodi can handle DRM properly yet.

Regards,
P.

**Comment by ghost** [comment]
Hy

No because ither channels that require silverlight are working fine. 

Regards

Ben

**Comment by nancpasc** [comment]
Try to see if available in "LiveTV - All channels". Syncing favorites may take up to two days

**Comment by ghost** [comment]
Sorry. Ard and vox sre missing in all channels. Never used favourites

**Comment by ghost** [comment]
Now another Channel is gone:'ZDF'

**Comment by nancpasc** [comment]
That's weird. 
Try to remove all the .cache files in %appdata%\Kodi\userdata\addon_data\plugin.video.zattoobox
and try again..

**Comment by ghost** [comment]
Kodi solves it. 

Thank you for your help!

Best regards Ben

**Comment by Nexolight** [comment]
Hey 

I have the same problem too. I don't really understand the meaning of "Kodi solves it". I cannot see the channels DMAX, SIXX; RTL, RTL II, 3+, Kabel 1, ORF and a few more. I live in Switzerland and should be able to see them as I am when I access Zattoo via PC or smartphone. This is a big deal since these are the main channels which I actually watch.

System: Kodi v 14.2 on LMDE 2 (Debian 8)

I reinstalled the plugin a few times as well as I have deleted the mentioned folders.

The mentioned channel "Sixx" disapperead between the 11.07.2015 and 12.07.2015 It seems to be something which is related to their configuration.

**Comment by nancpasc** [comment]
Hi @baerwurzl ,

Would be great if you could help.

Thanx a lot !

P.

**Comment by ghost** [comment]
Hy

Try to uncheck the option "fade out seen". (Sorry. Dont know how the option is called in english)

in channel view press left and in this menu there is the option to blend out seen movies etc. /show seen movies. This is the solution...

**Comment by nancpasc** [comment]
Thanks for the info !
