### ISSUE TITLE
Program guide

### ISSUE THREAD

**Issue by scrag** [nancpasc/ZattooBox#4]
Hi. Great addon.

Any chance of being able to incorporate the program guide into the addon?

Thank you

**Comment by nancpasc** [comment]
Hi. I might consider if I can find an already existing script or plugin to display a TV guide in Kodi. I keep the request open for now.

**Comment by capicecube** [comment]
Hi 

Amazing addon! Work perfect (I have tried native zattoo on AFTV stick, the android version - doesn't work as sideloaded app for lack of a mouse simulatore)...your solution is just fantastic!

Do you have some news for the EPG (program guide of Zattoo)? is the following guide of any use? http://kodi.wiki/view/PVR

And, as I'm already here: does your addon recognize my HiQ subscription of Zattoo?
thank you!

**Comment by nancpasc** [comment]
Hi.

I need to investigate more. I don't see a way to make a clean and useful TV program with current version of Kodi. Maybe a future version will add better support for EPG-like add-ons.

And yes the addon will work seamlessly with your HiQ subscription :)

Regards.

**Comment by nancpasc** [comment]
Hi,

A TV guide should be made available in the next release, thanks to community support :)

**Comment by scrag** [comment]
Fantastic News! Thank you very much.

**Comment by 23matt** [comment]
Great App! The stream runs a lot smoother than the browser version (on old MacBook Air). 
When will the next release be available? Is there a way to switch channels without always going back in the menu?

**Comment by coolcow** [comment]
Waiting for the next release too. I would love to use this great addon as a full replacement of my traditional TV, but currently, with the switch  behaviour (go back to menu and select a channel) it's to much a pain in the a**. So I still use my android app with Chromecast rather than Zattoobox on the pi...
Any expectations for the next release date ?

**Comment by nancpasc** [comment]
I unfortunately lost track of the contributor of this feature. I'll get it done myself but it may take some time; don't expect it to be ready before the end of the year. The feature stays open.

**Comment by rainman74** [comment]
Hallo,

da die Live-TV-Streams ja alle nicht mehr zuverlässig funktionieren, habe ich mir ein Zattoo-Abo zugelegt. Leider ist die Zattoo-eigene App auf FireTV zu träge und daher nutze ich auch das Plugin Zattoo-Box mit der EPG-Erweiterung von gdomenici. Ich habe damit den Menü-Eintrag "TV" ersetzt.

Nun würde ich aber gerne das PVR-Plugin IPTV Simple Client in einen "Plugin Simple Client" umschreiben, mit dem die Zattoo-Streams direkt vom Plugin geliefert werden können. Dazu kann man in Kodi für die Steuerung der Zattoo-Box entsprechene Command-Lines verwenden.

Die M3U-Datei würde dann beispielhaft so aussehen:
‪#‎EXTM3U‬
‪#‎EXTINF‬:-1 tvg-id="ARD.de" tvg-logo="ard.png",DAS ERSTE
plugin://plugin.video.zattoobox/?ext=LiveTV&mode=watch&id=ard
#EXTINF:-1 tvg-id="ZDF.de" tvg-logo="zdf.png",ZDF
plugin://plugin.video.zattoobox/?ext=LiveTV&mode=watch&id=zdf
#EXTINF:-1 tvg-id="RTL.de" tvg-logo="rtl.png",RTL
plugin://plugin.video.zattoobox/?ext=LiveTV&mode=watch&id=rtl_deutschland

Vorteile für diese Lösung wären:
- direkte Einbindung von Zattoo und auch weiteren TV-Plugins in das Kodi PVR-Framework
- es können alle Kodi-Standard PVR-Masken und Funktionen verwendet werden
- externes EPG kann weiter genutzt werden (z.B. Rytec)

Da ich nun aber noch keine Entwicklungserfahrung mit Kodi-Plugins habe - für das intensive Einlesen fehlt mir leider die Zeit: Wer kennt sich hier aus - am besten bereits mit dem IPTV Simple Client - und wer kann oder möchte hier mithelfen? Das Plugin würde dann auch hier Open Source zur Verfügung gestellt. Bei Interesse bitte melden.

Es wäre natürlich auch möglich, dass die Idee von nancpasc selbst aufgegriffen wird.

Vg

**Comment by coolcow** [comment]
Ich kann leider ebenfalls keinerlei Entwicklungserfahrung mit Kodi-Plugins aufweisen, biete mich aber als Tester sehr gerne an, da mich dieses Feature brennend interessiert (bin ebenfalls unzufriedener Zattoo@FireTV-Konsument) !

**Comment by rainman74** [comment]
Hello there,

since the free Live-TV streams all no longer function reliably, I've gained a Zattoo subscription. Unfortunately Zattoo's own app is too sluggish on FireTV and therefore I use the plugin Zattoo box with the EPG extension of gdomenici. I have therefore replaced the menu item "TV" with the plugin-page "live tv".

Now I would like to rewrite the PVR plugin "Simple IPTV client" into a "PLUGIN Simple client", with that the Zattoo streams can be delivered directly from the plugin to the PVR core.

The M3U file would look like as an example:
#EXTM3U
#EXTINF: -1 TVG id = "ARD.de" TVG logo = "ard.png" the first
plugin: //plugin.video.zattoobox/ ext = LiveTV & mode = watch & id = ard?
#EXTINF: -1 TVG id = "ZDF.de" TVG logo = "zdf.png" ZDF
plugin: //plugin.video.zattoobox/ ext = LiveTV & mode = watch & id = ZDF?
#EXTINF: -1 TVG id = "RTL.de" TVG logo = "rtl.png" RTL
plugin: //plugin.video.zattoobox/ ext = LiveTV & mode = watch & id = rtl_deutschland?

Advantages of this solution are:

```
direct integration of Zattoo and other TV/Stream-Plugins in the Kodi PVR framework
all Kodi standard PVR masks and functions are useable
external EPG could be used, too (eg Rytec)
```

But since I do not have any development experience with Kodi plugins yet, - for intensive reading unfortunately I lack the time: Who wants to help here? The plugin would then provided open source.

Of course, it would also be possible that the idea will be taken up by nancpasc or gdomenici itself.

Best regards

**Comment by rainman74** [comment]
Hi coolcow, prima vielen Dank für Deine Unterstützung. Sollte hier was
entstehen wirst Du natürlich eingebunden! :-)

Am 17. Dezember 2015 um 11:42 schrieb Jean-Michel Ruiz <
notifications@github.com>:

**Comment by rainman74** [comment]
I've searched for a PVR-API Documentation but without success... it seams that only Kodi core developers should write such Plugins.

As a workaround the Zattoo Box plugin possibly could write all Zattoo-Stream-URLs of Zattoos favorites incl. the required URL parameters in a local M3U file every time when Kodi starts or once a day. This in turn could be then included in PVR IPTV Simple Client.

I think this way would be very easy to implement, right?

Later I'll post an example for such a generated file.

**Comment by igugigu** [comment]
Someone added a program guide:
http://www.kodinerds.net/index.php/Thread/48314-Zattoo-und-EPG/?postID=263984#post263984

You can download a good working version from here:
https://drive.google.com/file/d/0B2Acxd6qjdZnYXBnYWpuak1VWm8/view?pref=2&pli=1

Can that be merged? (The author writes that he does not publish it because he does not want to maintain it).

[I'am still missing channel zapping -- change channel like on a normal tv]

**Comment by rainman74** [comment]
Hi igugigu, I know that plugin, it is very cool but also still very buggy! My intention was to write or chance an PVR client to use the official Kodi PVR API and not using a plugin.
Best Regards Kalle

**Comment by indritix** [comment]
Tried the ZatooboxExt (the EPG is a TVGuide fork) yesterday.
First I just copied/merged files to this (Zattoobox) plugin, and actually it partially worked (I could see an EPG but not switch to the live stream directly from there).
Then, I exited the GUI, and it broke.
Tried as a separate addon, and this time it didn't work at all.

**Comment by indritix** [comment]
update: 
the ZattooBoxExt actually works (although the GUI is a bit buggy).
The problem related to the previous post is that when selecting a channel directly from the EPG section, the stream wont start if I select "play from beginning".

Nevertheless if I select no, than the stream plays fine :)

In other words the replay function has some bugs, the rest seems to work.
Would be really nice if the plugin's EPG functionality could be integrated directly in the builtin KODI LiveTV EPG functionality.
This way the EPG would come up by just hitting the Guide button on the remote (very wifeproof)!

**Comment by hagba20** [comment]
I also use the ZattooBoxExt Addon in Kodi. 
The Replay Function in the EPG  and "Play from Beginning" works if you choose "Favorites" instead of "All Channels" in the Main Menu. You have to define only your favorites before with another device.

**Comment by hopgoodpaul** [comment]
Hi rainman74, did you manage to create an m3u file for zattoo? I'd love to be able to use the PVR Simple client plugin with zattoo. 

Or if there's an update to this plugin that would be awesome.

**Comment by igugigu** [comment]
http://pastebin.com/d8y1JgM9  placed in .kodi/userdata/playlists/video

works for me (running 1.x-contrib) as normal playlist

**Comment by hopgoodpaul** [comment]
Thanks @igugigu but for some reason it's not working for me. In the logs I see this when trying to play from the playlist file:

```
10:47:15 2364.486084 T:1958175280   DEBUG: Radio UECP (RDS) Processor - new CDVDRadioRDSData
10:47:15 2364.486572 T:1958175280  NOTICE: DVDPlayer: Opening: pvr://channels/tv/All channels/pvr.iptvsimple_1038442810.pvr
10:47:15 2364.486572 T:1958175280 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
10:47:15 2364.486816 T:1958175280   DEBUG: CRenderManager::UpdateDisplayLatency - Latency set to 0 msec
10:47:15 2364.487061 T:1958175280   DEBUG: CMMALRenderer::UnInitMMAL pool((nil))
10:47:15 2364.487061 T:1958175280   DEBUG: CMMALRenderer::PreInit
10:47:15 2364.487549 T:1753621488   DEBUG: Thread DVDPlayer start, auto delete: false
10:47:15 2364.488281 T:1753621488  NOTICE: Creating InputStream
10:47:15 2364.590576 T:1753621488   DEBUG: PVRManager - OpenLiveStream - opening live stream on channel 'prosieben'
10:47:15 2364.590820 T:1753621488   DEBUG: opening live stream on url 'plugin://plugin.video.zattoobox/?ext=LiveTV&mode=watch&id=prosieben'
10:47:15 2364.631104 T:1753621488   DEBUG: PVRFile - Open - playback has started on filename pvr://channels/tv/All channels/pvr.iptvsimple_1038442810.pvr
10:47:15 2364.632568 T:1753621488 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.zattoobox/?ext=LiveTV&mode=watch&id=prosieben
10:47:15 2364.632812 T:1753621488   ERROR: CDVDInputStreamPVRManager::Open - error opening [plugin://plugin.video.zattoobox/?ext=LiveTV&mode=watch&id=prosieben]
10:47:15 2364.633057 T:1753621488   ERROR: CDVDPlayer::OpenInputStream - error opening [pvr://channels/tv/All channels/pvr.iptvsimple_1038442810.pvr]
10:47:15 2364.633301 T:1753621488  NOTICE: CDVDPlayer::OnExit()
10:47:15 2364.633545 T:1753621488   DEBUG: CDVDInputStreamPVRManager::Close - stream closed
```

I installed 1.x-contrib and used your exact file from pastebin. Is there something obvious I'm missing in order to be able to open plugin:// urls? I've been googling this for a few hours and can't find anything really helpful. 
I'm running OSMC if that helps too.

**Comment by igugigu** [comment]
I'am not aware that support for plugin-urls came with an addon.

Are you using this playlist as source for PVR Simple? I just open the playlist via Videos->Files->Playlists (or something like that).

I'am not using PVR Simple, i just created this playlist and configured my remote so that i can use my remote to directly switch channels (zapping). [  PreviousChannel: <key id="211">Playlist.PlayOffset(-1)</key> ]

**Comment by nancpasc** [comment]
Thank you everyone for the support. Please now use the excellent Zattoo PVR Client to access this feature.

https://kodi.tv/addon/pvr-client/zattoo-pvr-client
